import { useEffect, useState } from 'react'
import { translateText } from './strings'
import { supabase } from './supabaseClient'
import './App.css'

const jobsSeed = [
  { id: 1, employer: 'शिव बिल्डर्स', skill: 'राजमिस्त्री', wage: 850, place: 'अंधेरी, मुंबई', time: 'आज', people: 3, status: 'खुला', tone: 'fair' },
  { id: 2, employer: 'नया घर साइट', skill: 'पेंटर', wage: 620, place: 'वाकड, पुणे', time: 'कल से', people: 2, status: 'खुला', tone: 'low' },
  { id: 3, employer: 'ग्रीन टॉवर्स', skill: 'बढ़ई', wage: 900, place: 'बोपल, अहमदाबाद', time: 'आज', people: 1, status: 'खुला', tone: 'high' },
]
const flags = { low: ['कम', 'यह रेट औसत से कम है'], fair: ['उचित', 'यह रेट ठीक है'], high: ['ज़्यादा', 'यह रेट औसत से ज़्यादा है'] }
function LanguageBridge({ language }) {
  useEffect(() => {
    document.documentElement.lang = language === 'en' ? 'en' : 'hi'
    if (language !== 'en') return undefined
    const translate = node => {
      if (node.nodeType === Node.TEXT_NODE) node.nodeValue = translateText(node.nodeValue)
      if (node.nodeType === Node.ELEMENT_NODE && !node.closest('.language-switch,.wordmark,.brand')) {
        const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT)
        let textNode; while ((textNode = walker.nextNode())) {
          if (!textNode.parentElement.closest('.language-switch,.wordmark,.brand')) textNode.nodeValue = translateText(textNode.nodeValue)
        }
      }
    }
    const root = document.getElementById('root'); translate(root)
    const observer = new MutationObserver(records => records.forEach(record => record.addedNodes.forEach(translate)))
    observer.observe(root, { childList: true, subtree: true })
    return () => observer.disconnect()
  }, [language])
  return null
}
function WageFlag({ tone = 'fair', compact = false }) { return <span className={`wage-flag ${tone} ${compact ? 'compact' : ''}`}><b>{tone === 'low' ? '↓' : tone === 'high' ? '↑' : '✓'}</b>{flags[tone][0]}</span> }
function Header({ role, onHome }) { return <header><button className="brand" onClick={onHome}><i>क</i><strong>कामसेतु</strong></button><div className="role-pill">{role}</div><button className="bell" aria-label="सूचनाएँ">♧<em /></button></header> }
function JobCard({ job, onApply }) { return <article className="job-card"><div className="job-head"><div className="job-icon">{job.skill === 'पेंटर' ? '🖌️' : job.skill === 'बढ़ई' ? '🪚' : '🧱'}</div><div className="job-title"><h3>{job.skill}</h3><p>{job.employer}</p></div><WageFlag tone={job.tone} compact /></div><div className="job-info"><span>📍 {job.place}</span><span>👥 {job.people} मज़दूर</span><span>🕐 {job.time}</span></div><div className="job-bottom"><div><strong>₹{job.wage}</strong><small> रोज़ का</small></div><button className="small-action" onClick={() => onApply(job)}>हाथ उठाएँ <b>›</b></button></div></article> }
function Landing({ choose }) { return <main className="landing"><div className="landing-top"><div className="logo-large"><i>क</i></div><div className="wordmark">काम<span>सेतु</span></div><p>मेहनत का सही दाम</p></div><div className="hero-illustration"><div className="sun" /><div className="buildings">▥ ▥ ▥</div><div className="workers">👷🏽‍♀️ <span>🤝</span> 👷🏽</div></div><section className="choice-card"><p>आपको क्या चाहिए?</p><button className="choice worker" onClick={() => choose('worker')}><span>👷🏽</span><b>मुझे काम चाहिए</b><i>›</i></button><button className="choice employer" onClick={() => choose('employer')}><span>🏗️</span><b>मुझे मज़दूर चाहिए</b><i>›</i></button><button className="contractor-link" onClick={() => choose('contractor')}>🧰 मैं ठेकेदार हूँ <b>›</b></button></section><footer>कामसेतु · भरोसे का साथ</footer></main> }
function AuthScreen({ role, onBack, onDone }) {
  const [phone, setPhone] = useState(''); const [code, setCode] = useState(''); const [phase, setPhase] = useState('phone'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const labels = { worker: ['👷🏽', 'काम चाहिए', 'अपने नंबर से आगे बढ़ें'], contractor: ['🧰', 'ठेकेदार प्रवेश', 'अपना नंबर लिखें'], employer: ['🏗️', 'नियोक्ता प्रवेश', 'काम की जगह खोजें'] }[role]
  const sendCode = async () => {
    if (phone.replace(/\D/g, '').length < 10) return setError('सही मोबाइल नंबर लिखें')
    setBusy(true); setError('')
    if (supabase) { const { error: authError } = await supabase.auth.signInWithOtp({ phone: `+91${phone.replace(/\D/g, '').slice(-10)}` }); if (authError) { setError('कोड नहीं भेजा गया'); setBusy(false); return } }
    setBusy(false); setPhase('code')
  }
  const verify = async () => {
    if (!supabase && code !== '123456') return setError('कोड फिर से लिखें')
    setBusy(true); setError('')
    if (supabase) { const { error: authError } = await supabase.auth.verifyOtp({ phone: `+91${phone.replace(/\D/g, '').slice(-10)}`, token: code, type: 'sms' }); if (authError) { setError('कोड सही नहीं है'); setBusy(false); return } }
    setBusy(false); onDone()
  }
  return <main className="auth-page"><button className="back auth-back" onClick={onBack}>‹</button><div className="auth-mark">{labels[0]}</div><h1>{labels[1]}</h1><p>{labels[2]}</p>{phase === 'phone' ? <><label>मोबाइल नंबर</label><div className="phone-input"><span>+91</span><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="मोबाइल नंबर" maxLength="10" autoFocus/></div><small className="privacy">🔒 आपका नंबर सुरक्षित है</small><button className="primary wide" onClick={sendCode} disabled={busy}>{busy ? 'थोड़ा रुकें' : 'कोड भेजें'}</button></> : <><label>छह अंकों का कोड</label><input className="otp-input" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g, '').slice(0,6))} inputMode="numeric" placeholder="● ● ● ● ● ●" autoFocus/><p className="otp-note">{supabase ? 'मोबाइल पर आया कोड लिखें' : 'डेमो कोड: 123456'}</p><button className="primary wide" onClick={verify} disabled={busy}>{busy ? 'थोड़ा रुकें' : 'आगे बढ़ें'}</button><button className="resend" onClick={sendCode}>कोड फिर भेजें</button></>}{error && <div className="auth-error">⚠ {error}</div>}<footer>कामसेतु · भरोसे का साथ</footer></main>
}
function WorkerHome({ onHome }) {
  const [jobs, setJobs] = useState(jobsSeed); const [active, setActive] = useState('accepted'); const [notice, setNotice] = useState(''); const [tab, setTab] = useState('jobs'); const [filter, setFilter] = useState('all')
  const apply = job => { setJobs(jobs.map(j => j.id === job.id ? { ...j, status: 'आवेदन किया' } : j)); setNotice(`${job.employer} को आपका आवेदन पहुँचा`) }
  const complete = () => { setActive('completed'); setNotice('काम पूरा हुआ · भरोसे का स्कोर बढ़ा') }
  const filteredJobs = filter === 'all' ? jobs : filter === 'mason' ? jobs.filter(job => job.skill === 'राजमिस्त्री') : jobs.filter(job => job.place.includes('मुंबई'))
  const jobFeed = <><div className="filter-row"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>सब काम</button><button className={filter==='mason'?'active':''} onClick={()=>setFilter('mason')}>राजमिस्त्री</button><button className={filter==='nearby'?'active':''} onClick={()=>setFilter('nearby')}>पास में</button></div><section className="section-title"><h2>आपके लिए काम</h2><span>{filteredJobs.length} काम</span></section><div className="job-list">{filteredJobs.map(j => j.status === 'आवेदन किया' ? <article className="job-card applied" key={j.id}><div className="job-head"><div className="job-icon">🧱</div><div className="job-title"><h3>{j.skill}</h3><p>{j.employer}</p></div><WageFlag tone={j.tone} compact/></div><div className="accepted-state">✓ आपका आवेदन भेजा गया</div></article> : <JobCard key={j.id} job={j} onApply={apply}/>)}</div></>
  const myJobs = <><section className="section-title"><h2>मेरे काम</h2><span>2 काम</span></section><article className="job-card"><div className="job-head"><div className="job-icon">🧱</div><div className="job-title"><h3>राजमिस्त्री</h3><p>शिव बिल्डर्स · अंधेरी</p></div><span className="wage-flag fair">✓ मंज़ूर</span></div><div className="job-bottom"><div><strong>₹850</strong><small> रोज़ का</small></div>{active === 'completed' ? <span className="accepted-state">✓ काम पूरा</span> : <><a className="call-btn" href="tel:+919876543210">☎ कॉल करें</a><button className="small-action" onClick={complete}>काम पूरा</button></>}</div></article><article className="job-card applied"><div className="job-head"><div className="job-icon">🖌️</div><div className="job-title"><h3>पेंटर</h3><p>नया घर साइट</p></div></div><div className="accepted-state">✓ जवाब का इंतज़ार</div></article></>
  const account = <><section className="section-title"><h2>मेरा खाता</h2></section><article className="job-card profile-card"><div className="job-head"><div className="job-icon">👷🏽</div><div className="job-title"><h3>राजू कुमार</h3><p>राजमिस्त्री · मुंबई</p></div><b>4.9 ★</b></div><div className="job-info"><span>📱 +91 98765 43210</span><span>✓ पहचान पूरी</span></div></article><button className="post-button" onClick={onHome}>↪ बाहर जाएँ</button></>
  return <div className="app-shell"><Header role="मज़दूर" onHome={onHome}/><main className="screen worker-screen"><div className="hello"><div><p>नमस्ते, राजू 👋</p><h1>{tab==='jobs'?'आज का काम':tab==='my'?'मेरे काम':'मेरा खाता'}</h1></div><button className="location">📍 मुंबई⌄</button></div><div className="earnings"><div><span>इस हफ़्ते की कमाई</span><strong>₹ 4,250</strong></div><div className="score"><b>{active === 'completed' ? '4.9' : '4.8'}</b><span>★ भरोसे का स्कोर</span></div></div>{notice && <div className="toast">✓ {notice}</div>}{tab==='jobs' && active !== 'completed' && <article className="job-card accepted-job"><div className="job-head"><div className="job-icon">🧱</div><div className="job-title"><h3>आज का पक्का काम</h3><p>शिव बिल्डर्स · अंधेरी</p></div><span className="wage-flag fair">✓ मंज़ूर</span></div><div className="job-bottom"><div><strong>₹850</strong><small> रोज़ का</small></div><a className="call-btn" href="tel:+919876543210">☎ कॉल करें</a><button className="small-action" onClick={complete}>काम पूरा</button></div></article>}{tab==='jobs'?jobFeed:tab==='my'?myJobs:account}</main><nav><button className={tab==='jobs'?'selected':''} onClick={()=>setTab('jobs')}>⌂<span>काम</span></button><button className={tab==='my'?'selected':''} onClick={()=>setTab('my')}>▣<span>मेरे काम</span></button><button className={tab==='account'?'selected':''} onClick={()=>setTab('account')}>◉<span>खाता</span></button></nav></div>
}
function ContractorHome({ onHome }) { const [rate, setRate] = useState(780); const [logged, setLogged] = useState(false); const avg = logged ? 784 : 760; const tone = rate < avg*.9 ? 'low' : rate > avg*1.1 ? 'high' : 'fair'; return <div className="app-shell"><Header role="ठेकेदार" onHome={onHome}/><main className="screen contractor-screen"><div className="hello"><div><p>नमस्ते, सुरेश 👋</p><h1>आज का हिसाब</h1></div><button className="location">📍 मुंबई⌄</button></div><div className="crew-card"><div><span className="crew-icon">👷🏽‍♂️</span><p>मेरी टोली</p><strong>12 <small>मज़दूर</small></strong></div><button>+ मज़दूर जोड़ें</button></div><section className="rate-panel"><div className="panel-top"><div><span>आज का शहर भाव</span><h2>राजमिस्त्री</h2></div><WageFlag tone="fair"/></div><div className="average"><strong>₹{avg}</strong><span>औसत रोज़ का</span><em>↑ {logged ? '₹24 बढ़ा' : '₹18 बढ़ा'}</em></div><div className="rate-line"><span>सरकारी कम से कम</span><b>₹650</b></div></section><section className="log-card"><h2>आज की मज़दूरी लिखें</h2><p>इससे सबको सही भाव मिलेगा</p><div className="rate-input"><button onClick={()=>setRate(Math.max(100,rate-10))}>−</button><strong>₹ {rate}</strong><button onClick={()=>setRate(rate+10)}>+</button></div><div className="live-flag"><span>आपका रेट</span><WageFlag tone={tone}/><small>{flags[tone][1]}</small></div><button className="primary wide" onClick={()=>setLogged(true)}>{logged ? '✓ आज की मज़दूरी लिखी गई' : '₹ आज की मज़दूरी लिखें'}</button></section></main><nav><button className="selected">⌂<span>हिसाब</span></button><button>♧<span>मेरी टोली</span></button><button>◉<span>खाता</span></button></nav></div> }
function EmployerHome({ onHome }) { const [view, setView] = useState('home'); const [wage,setWage] = useState(800); const [posted,setPosted]=useState(false); const tone=wage<684?'low':wage>836?'high':'fair'; if(view==='post') return <div className="app-shell"><Header role="नियोक्ता" onHome={onHome}/><main className="screen post-screen"><button className="back" onClick={()=>setView('home')}>‹</button><h1>नया काम लगाएँ</h1><p className="hint">साफ़ जानकारी दें</p><label>काम किसका है?</label><div className="select-box">🧱 राजमिस्त्री <b>⌄</b></div><label>काम की जगह</label><div className="select-box">📍 अंधेरी, मुंबई <b>⌄</b></div><label>रोज़ का दाम</label><div className="wage-field"><span>₹</span><input value={wage} onChange={e=>setWage(Number(e.target.value)||0)} inputMode="numeric"/><small>रुपये</small></div><div className="fair-preview"><div><span>आज का शहर भाव</span><strong>₹760 <small>रोज़ का</small></strong></div><WageFlag tone={tone}/><p>{flags[tone][1]}</p></div><button className="primary wide" onClick={()=>{setPosted(true);setView('home')}}>काम लगाएँ</button></main></div>; return <div className="app-shell"><Header role="नियोक्ता" onHome={onHome}/><main className="screen employer-screen"><div className="hello"><div><p>नमस्ते, शिव बिल्डर्स 👋</p><h1>आपके काम</h1></div><button className="avatar">शि</button></div><div className="employer-summary"><div><span>खुले काम</span><b>{posted?2:1}</b></div><div><span>नए आवेदन</span><b>6 <em>•</em></b></div><div><span>काम पूरे</span><b>18</b></div></div><button className="post-button" onClick={()=>setView('post')}><span>＋</span> नया काम लगाएँ</button><section className="section-title"><h2>चल रहे काम</h2><span>सब देखें ›</span></section><article className="job-card employer-job"><div className="job-head"><div className="job-icon">🧱</div><div className="job-title"><h3>राजमिस्त्री चाहिए</h3><p>अंधेरी, मुंबई</p></div><WageFlag compact /></div><div className="job-bottom"><div><strong>₹850</strong><small> रोज़ का</small></div><button className="applicants">👥 4 आवेदन <b>›</b></button></div></article><section className="section-title"><h2>हाल की जानकारी</h2></section><div className="activity"><span>✓</span><p><b>काम पूरा हुआ</b><small>पेंटर · 2 मज़दूर</small></p><em>कल</em></div></main><nav><button className="selected">⌂<span>काम</span></button><button>♧<span>आवेदन</span><i>6</i></button><button>◉<span>खाता</span></button></nav></div> }
function App(){
  const [role,setRole]=useState(null); const [signedIn, setSignedIn] = useState(false); const [language, setLanguage] = useState('hi')
  const home = () => { setRole(null); setSignedIn(false) }
  const view = !role ? <Landing choose={setRole}/> : !signedIn ? <AuthScreen role={role} onBack={home} onDone={()=>setSignedIn(true)}/> : role==='worker' ? <WorkerHome onHome={home}/> : role==='contractor' ? <ContractorHome onHome={home}/> : <EmployerHome onHome={home}/>
  return <><LanguageBridge language={language}/><button className="language-switch" onClick={() => setLanguage(language === 'hi' ? 'en' : 'hi')} aria-label={language === 'hi' ? 'भाषा बदलें' : 'Change language'}>{language === 'hi' ? 'English' : 'Hindi'}</button><div key={language}>{view}</div></>
}
export default App
